version: '3'
services:
  app:
    build:
      context: .
      dockerfile: infra/Dockerfile
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/app
      - ./infra/prod.ini:/usr/local/etc/php/conf.d/prod.ini
    working_dir: /app
    depends_on:
      - database
      - cache
    networks:
      - laravel
  web:
    image: nginx:1.25
    ports:
      - "8123:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./storage/app/public:/app/public/storage
    depends_on:
      - app
    networks:
      - laravel
  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "aisolutions"
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "bradoc"
      MYSQL_PASSWORD: "123456"
    ports:
      - "3306:3306"
    volumes:
      - ./infra/mysql:/var/lib/mysql
    networks:
      - laravel
  mailpit:
    image: axllent/mailpit:v1.6.13
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel
  cache:
    image: redis:7
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
